### PR TITLE
Filter

### PR DESCRIPTION
**Pull request by RahullRawat**
- Filter by category
- search
- mobile menu

https://deploy-preview-10--cricket-classics.netlify.app/

### CODE REVIEW

**Review by BISINIGISHIVANI — APPROVED** [review]
all functionalities working as intended.good to merge @RahullRawat

**Comment by gadgetfather** [comment]
You can write media query to hide the mobile side after certain breakpoint
image

**Comment by gadgetfather** [comment]
Search and filters and working perfectly, great work @RahullRawat

**Review by gadgetfather — APPROVED** [review]

**Review by lomesshh — APPROVED** [review]
clean and modular code
filters working as expected
looks good to merge

**Pull request merged**
